added rofi theme as an argument for menugen

diff --git a/menugen b/menugen
--- a/menugen
+++ b/menugen
@@ -5,25 +5,19 @@
 # $2 - Prompt text (a string)
 # $3 - Auto-selection option (a boolean)
 function RENDERMENU() {
-	if [[ $# -ne 3 ]]; then
-		>&2 echo "ERROR: RENDERMENU requires 3 arguments (got $#)"
+	if [[ $# -ne 4 ]]; then
+		>&2 echo "ERROR: RENDERMENU requires 4 arguments (got $#)"
 		>&2 echo "    - The menu content (value: \"$1\")"
 		>&2 echo "    - The prompt text (value: \"$2\")"
 		>&2 echo "    - Boolean for autoselect (value: \"$3\")"
+		>&2 echo "    - Theme to apply (value: \"$4\")"
 		exit -1
 	fi
 	if [[ "$(uname)" == "Linux" ]]; then
 		if [[ "$3" == true ]]; then
-			echo -e "$1" | rofi -dmenu -p "$2"
+			echo -e "$1" | rofi -dmenu -p "$2" -theme $4
 		else
-			echo -e "$1" | rofi -dmenu -p "$2"
-		fi
-	fi
-	if [[ "$(uname)" == "Darwin" ]]; then
-		if [[ "$3" == true ]]; then
-			echo -e "$1" | xmenu -H 20 -p "$2"
-		else
-			echo -e "$1" | xmenu -H 20 -p "$2"
+			echo -e "$1" | rofi -dmenu -p "$2" -theme $4
 		fi
 	fi
 }
